import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import PreguntasProteccion3 from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasProteccion3.jsx";
import PreguntasRiesgosMecanicos from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasRiesgosMecanicos.jsx";
import PreguntasRiesgosTermicos from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasRiesgosTermicos.jsx";
// import DragAndDropManos from "./pages/actividades/actividades_morelco_riesgos_manos/DragAndDropManos.jsx";
// import SelectAndValidateMobile from "./pages/actividades/actividades_morelco_riesgos_manos/SelectAndValidateMobile.jsx";
import PreguntasSeleccionHerramientas from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasSeleccionHerramientas.jsx";
import OrdenarPasos from "./pages/actividades/actividades_morelco_riesgos_manos/OrdenarPasos.jsx";
import OrdenarPasosPalmaManos from "./pages/actividades/actividades_morelco_riesgos_manos/OrdenarPasosPalmaManos.jsx";
import OrdenarPasosMobile from "./pages/actividades/actividades_morelco_riesgos_manos/OrdenarPasosMobile.jsx";
import Pregunta1alturas from "./pages/actividades/actividades_trabajo_seguro_alturas/Pregunta1alturas.jsx";
import Pregunta2alturas from "./pages/actividades/actividades_trabajo_seguro_alturas/Pregunta2alturas.jsx";
import SeleccionImagenesAlturas from "./pages/actividades/actividades_trabajo_seguro_alturas/SeleccionImagenesAlturas.jsx";
import DragAndDropAlturas1 from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropAlturas1.jsx";
import DragAndDropAlturas1Movil from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropAlturas1Movil.jsx";
import CardsInfoAlturas from "./pages/actividades/actividades_trabajo_seguro_alturas/CardsInfoAlturas.jsx";
import DragAndDrop from "./pages/actividades/actividades_morelco_riesgos_manos/DragAndDrop.jsx";
import PreguntasTiposRiesgo from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasTiposRiesgo.jsx";
import PreguntasTiposRiesgoMobile from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasTiposRiesgoMobile.jsx";
import PreguntasVorF from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasVorF.jsx";
import ActividadListaDesplegable from "./pages/actividades/actividades_morelco_riesgos_manos/ActividadListaDesplegable.jsx";
import PreguntasAlturas1 from "./pages/actividades/actividades_trabajo_seguro_alturas/PreguntasAlturas1.jsx";
import DragAndDropAlturas2 from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropAlturas2.jsx";
import DragAndDropAlturas2Movil from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropAlturas2Movil.jsx";
import ActividadFalsoVerdadero from "./pages/actividades/actividades_espacios_confinados/Actividad_Falso_Verdadero.jsx";
import Drag_And_Drop from "./pages/actividades/actividades_espacios_confinados/Drag_And_Drop.jsx";
// import Drag_And_DropMobile from "./pages/actividades/actividades_espacios_confinados/Drag_And_DropMobile.jsx";
import EPSLugaresConfinados from "./pages/actividades/actividades_espacios_confinados/EPS_Lugares_Confinados.jsx";
import ActividadMobileEntradaSalida from "./pages/actividades/actividades_espacios_confinados/Actividad_Mobile_Entrada_Salida.jsx";
import OrdenarPasosPalmaManosMobile from "./pages/actividades/actividades_morelco_riesgos_manos/OrdenarPasosPalmaManosMobile.jsx";
import PreguntasSiNo from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasSiNo.jsx";
import EspaciosConfinadosSeleccionMultiple from "./pages/actividades/actividades_morelco_riesgos_manos/EspaciosConfinadosSeleccionMultiple.jsx";
import SeleccionEspaciosConfinados from "./pages/actividades/actividades_morelco_riesgos_manos/SeleccionEspaciosConfinados.jsx";
import "./main.css";
import Slider13_Lista_desplegable from "./pages/actividades/actividades_espacios_confinados/Slider13_Lista_desplegable.jsx";
import Slider13_Lista_desplegable_movil from "./pages/actividades/actividades_espacios_confinados/Slider13_Lista_desplegable_movil.jsx";
import DragAndDropAudios from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropAudios.jsx";
import DragAndDropAudiosMovil from "./pages/actividades/actividades_espacios_confinados/DragAndDropAudiosMovil.jsx";
import Palabra_CorrectaMovil from "./pages/actividades/actividades_espacios_confinados/Slider13_Lista_desplegable_movil.jsx";
import Slider12_drag_and_drop_audios_movil from "./pages/actividades/actividades_espacios_confinados/Slider12_drag_and_drop_audios_movil.jsx";
import Slider14_Lista_desplegable from "./pages/actividades/actividades_espacios_confinados/Slider14_Lista_desplegable.jsx";
import Slider14_Lista_desplegable_movil from "./pages/actividades/actividades_espacios_confinados/Slider14_Lista_desplegable_movil.jsx";
import Slider12_drag_and_drop_audios from "./pages/actividades/actividades_espacios_confinados/Slider12_drag_and_drop_audios.jsx";
import Slider15_Lista_desplegable from "./pages/actividades/actividades_espacios_confinados/Slider15_Lista_desplegable.jsx";
import Slider15_Lista_desplegable_movil from "./pages/actividades/actividades_espacios_confinados/Slider15_Lista_desplegable_movil.jsx";
import PreguntasRiesgosTermicosV2 from "./pages/actividades/actividades_morelco_riesgos_manos/PreguntasRiesgosTermicosV2.jsx";
import Sliderppt24_SeleccionMultiple from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt24_SeleccionMultiple.jsx";
import Sliderppt9_DragAndDrop from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt9_DragAndDrop.jsx";
import Sliderppt15_SeleccionMultipleCheckbox from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt15_SeleccionMultipleCheckbox.jsx";
import Sliderppt16_SeleccionPreguntasParte1 from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt16_SeleccionPreguntasParte1.jsx";
import Sliderppt17_SeleccionPreguntasParte2 from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt17_SeleccionPreguntasParte2.jsx";
import Sliderppt26_PreguntasTF from "./pages/actividades/actividades_uso_seguro_andamios/Sliderppt26_PreguntasTF.jsx";
import Sliderppt18_SeleccionPreguntas from "./pages/actividades/actividades_pesv/Sliderppt18_SeleccionPreguntas.jsx";
import Sliderppt19_SeleccionPreguntasAudios from "./pages/actividades/actividades_pesv/Sliderppt19_SeleccionPreguntasAudios.jsx";
import PreguntasFactorHumanoTF from "./pages/actividades/actividades_pesv/PreguntasFactorHumanoTF.jsx";
import PreguntasFactorHumano from "./pages/actividades/actividades_pesv/PreguntasFactorHumano.jsx";
import OrdenarElementos from "./pages/actividades/actividades_pesv/OrdenarElementos.jsx";
import PPT14_EscogerOpcionSirena from "./pages/actividades/actividades_pesv/PPT14_EscogerOpcionSirena.jsx";
import SlidePP11_seleccione from "./pages/actividades/actividades_pesv/SlidePP11_seleccione.jsx";
import Sliderppt8_seleccione from "./pages/actividades/actividades_izaje_cargas/Sliderppt8_seleccione.jsx";
import Sliderppt13_seleccione_audio from "./pages/actividades/actividades_izaje_cargas/Sliderppt13_seleccione_audio.jsx";
import Sliderppt15_dragandrop_audios from "./pages/actividades/actividades_izaje_cargas/Sliderppt15_dragandrop_audios.jsx";
import Sliderppt16_seleccione_multiple from "./pages/actividades/actividades_izaje_cargas/Sliderppt16_seleccione_multiple.jsx";
import Sliderppt18_seleccione_multiple from "./pages/actividades/actividades_izaje_cargas/Sliderppt18_seleccione_multiple.jsx";
import Sliderppt25_preguntasTF from "./pages/actividades/actividades_izaje_cargas/Sliderppt25_preguntasTF.jsx";
import Slidermobile_select_audios from "./pages/actividades/actividades_izaje_cargas/Slidermobile_select_audios.jsx";
import PicadurasAnimalesPeligrosos from "./pages/actividades/actividades_riesgo_biologico/PicadurasAnimalesPeligrosos.jsx";
import Sliderppt15_SeleccionPreguntasAudios from "./pages/actividades/actividades_riesgo_psicosocial/Sliderppt15_SeleccionPreguntasAudios.jsx";
import DragAndDrop_Sistema_Oxiacetileno from "./pages/actividades/actividades_soldaduras/DragAndDrop_Sistema_Oxiacetileno.jsx";
import DragAndDrop_Sistema_OxiacetilenoMobile from "./pages/actividades/actividades_soldaduras/DragAndDrop_Sistema_OxiacetilenoMobile.jsx";
import Seleccione_EPP_Soldadura from "./pages/actividades/actividades_soldaduras/Seleccione_EPP_Soldadura.jsx";
import Seleccione_EPP_SoldaduraMobile from "./pages/actividades/actividades_soldaduras/Seleccione_EPP_SoldaduraMobile.jsx";
import ChileDAD from "./pages/actividades/actividades_morelco_riesgos_manos/ChileDAD.jsx";
import ChileSeleccione from "./pages/actividades/actividades_morelco_riesgos_manos/ChileSeleccione.jsx";
import PreguntasSeleccioneSiNo from "./pages/actividades/actividades_riesgo_psicosocial/PreguntasSeleccioneSiNo.jsx";
import Slider10SeleccioneMultiple from "./pages/actividades/actividades_riesgo_psicosocial/Slider10SeleccioneMultiple.jsx";
import Slider11SeleccioneMultipleV2 from "./pages/actividades/actividades_riesgo_psicosocial/Slider11SeleccioneMultipleV2.jsx";
import DragAndDropArisM from "./pages/actividades/actividades_aris_mining/DragAndDropArisM.jsx";
import IdentificarRiesgosBiologicos from "./pages/actividades/actividades_riesgo_biologico/IdentificarRiesgosBiologicos.jsx";
import OrdenarMedidasCorrectivas from "./pages/actividades/actividades_riesgo_biologico/OrdenarMedidasCorrectivas.jsx";
import DragAndDropSlide9 from "./pages/actividades/actividades_trabajo_seguro_alturas/DragnAndDropSlide9.jsx";
import DragAndDropSlide9Movil from "./pages/actividades/actividades_trabajo_seguro_alturas/DragAndDropSlide9Movil.jsx";
import PPT8_List_Desplegable from "./pages/actividades/actividades_pesv/PPT8_List_Desplegable.jsx";
import PPT_10_Preguntas from "./pages/actividades/herramientas_de_poder/PPT_10_Preguntas.jsx";
import PPT_11_List_Desplegable from "./pages/actividades/herramientas_de_poder/PPT_11_Lista_Desplegable.jsx";
import PPT_19_Preguntas from "./pages/actividades/herramientas_de_poder/PPT_19_Preguntas.jsx";
import PPT_21_DragAndDrop from "./pages/actividades/actividades_pesv/PPT_21_DragAndDrop.jsx";
import PPT_21_DragAndDrop_Mobile from "./pages/actividades/actividades_pesv/PPT_21_DragAndDrop_Mobile.jsx";
import PPT_22_Preguntas from "./pages/actividades/herramientas_de_poder/PPT_22_Preguntas.jsx";
import PPT_09_DragAndDrop from "./pages/actividades/actividades_izajes_de_cargas/PPT_09_DragAndDrop.jsx";
import PPT_09_DragAndDrop_Mobile from "./pages/actividades/actividades_izajes_de_cargas/PPT_09_DragAndDrop_Mobile.jsx";
import PPT_17_SeleccionMultiple from "./pages/actividades/actividades_izajes_de_cargas/PPT_17_SeleccionMultiple.jsx";
import PPT_21_Preguntas from "./pages/actividades/actividades_izajes_de_cargas/PPT_21_Preguntas.jsx";
import PPT_27_Lista_desplegable_imagen from "./pages/actividades/actividades_izajes_de_cargas/PPT_27_Lista_desplegable_imagen.jsx";
import PPT_11_ListaDesplegable_Audios from "./pages/actividades/actividades_izajes_de_cargas/PPT_11_ListaDesplegable_Audios.jsx";
import DnD_Conceptos_Clave from "./pages/actividades/actividades_tecnitanques_soldadura/DnD_Conceptos_Clave.jsx";
import IdentificaRolSoldadura from "./pages/actividades/actividades_tecnitanques_soldadura/IdentificaRolSoldadura.jsx";
import ActividadApoyoSocial from "./pages/actividades/actividades_riesgo_psicosocial/ActividadApoyoSocial.jsx";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <DragAndDropAlturas2 />
  </React.StrictMode>
);
